### ISSUE TITLE
Gameflow chart

### ISSUE THREAD

**Issue by DariusCorneciu** [Epure-Tofanel-Carlo/Unity#15]
### Exemplu
![hovglxes2](https://github.com/Epure-Tofanel-Carlo/Unity/assets/116907008/ddeae690-e12d-40f9-af4a-02e53de7c43c)

**Comment by Epure-Tofanel-Carlo** [comment]
![Untitled Diagram drawio](https://github.com/Epure-Tofanel-Carlo/Unity/assets/129178776/c1519608-daba-4f9f-9b59-df1c2d0fc055)
