### ISSUE TITLE
Activitati Secundare

### ISSUE THREAD

**Issue by DariusCorneciu** [Epure-Tofanel-Carlo/Unity#5]
**Ca un** jucator, **Vreau sa** particip la activitati secundare, cum ar fi: pescuitul, mineritul, vanarea monstrilor si agricultura. **Astfel incat** sa pot castiga bani pentru a juca taverna.

**Comment by Epure-Tofanel-Carlo** [comment]
Acestea au fost realizate, urmeaza sa le dam polish, dau close la issue.
