### ISSUE TITLE
Sistem Farming

### ISSUE THREAD

**Issue by DariusCorneciu** [Epure-Tofanel-Carlo/Unity#8]
**Ca un** jucator fermier, **Vreau sa** am la dispozitie cat mai multe structuri, unelte, si plante de crescut, **Astfel incat** sa pot vedea un progres fizic in ferma mea, sa obtin bani si sa ajung la deblocarea unei alte abilitati speciale.

**Comment by Epure-Tofanel-Carlo** [comment]
A fost adaugat. Dau close la Issue
